adaptive_noise_scale = 0
ae = "D:/BaiduSyncdisk/DyVault/Finetune/Models/ae.safetensors"
blocks_to_swap = 0
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
caption_extension = ".txt"
clip_skip = 1
discrete_flow_shift = 3
double_blocks_to_swap = 0
dynamo_backend = "no"
enable_bucket = true
epoch = 6
gradient_accumulation_steps = 1
guidance_scale = 3.5
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
keep_tokens = 0
learning_rate = 1e-5
learning_rate_te = 1e-5
logging_dir = "D:/BaiduSyncdisk/DyVault/Finetune/Models_Output"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 1600
min_bucket_reso = 256
mixed_precision = "fp16"
model_prediction_type = "sigma_scaled"
multires_noise_discount = 0.3
multires_noise_iterations = 0
noise_offset = 0
noise_offset_type = "Original"
optimizer_type = "AdamW"
output_dir = "D:/BaiduSyncdisk/DyVault/Finetune/Models_Output"
output_name = "last"
persistent_data_loader_workers = 0
pretrained_model_name_or_path = "D:/BaiduSyncdisk/DyVault/Finetune/Models/flux-dev-fp8/flux-dev-fp8.safetensors"
prior_loss_weight = 1
resolution = "512,512"
sample_prompts = "D:/BaiduSyncdisk/DyVault/Finetune/Models_Output\\sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 2
save_model_as = "safetensors"
save_precision = "fp16"
single_blocks_to_swap = 0
t5xxl_max_token_length = 512
timestep_sampling = "sigma"
train_batch_size = 1
train_blocks = "all"
train_data_dir = "D:/BaiduSyncdisk/DyVault/Finetune/Datasets/Custom_Images_Keai"
wandb_run_name = "last"
xformers = true
